# Generated by Django 6.0.6 on 2026-06-11 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='شماره اتاق')),
                ('room_type', models.CharField(choices=[('standard', 'استاندارد'), ('vip', 'وی\u200cآی\u200cپی (VIP)'), ('suite', 'سوئیت')], default='standard', max_length=20, verbose_name='نوع اتاق')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='ظرفیت (نفر)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر شب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/آماده سرویس')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out_date', models.DateField(verbose_name='تاریخ خروج')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='هزینه کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'پایان اقامت')], default='pending', max_length=15, verbose_name='وضعیت رزرو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سیستم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='مسافر')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.room', verbose_name='اتاق')),
            ],
        ),
    ]
