# Generated by Django 6.0.6 on 2026-06-12 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('valid_until', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس (مثلاً مینی\u200cبار، ترانسفر فرودگاه)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت سرویس')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود در هتل')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=4, verbose_name='درصد مالیات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور فاکتور')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='hotel.booking')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.coupon')),
                ('services', models.ManyToManyField(blank=True, to='hotel.service', verbose_name='خدمات اضافه شده')),
            ],
        ),
    ]
