# Generated by Django 6.0.6 on 2026-06-12 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_coupon_service_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ بیعانه پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت بیعانه (موقت)'), ('confirmed', 'تایید شده (اتاق قفل شد)'), ('checked_out', 'تسویه شده و خروج کامل'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت رزرو'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='هزینه کل اتاق'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تسویه کامل نهایی؟'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotel.service', verbose_name='خدمات استفاده شده'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / قابل رزرو'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'یک تخته'), ('double', 'دو تخته'), ('suite', 'سوئیت'), ('vip', 'VIP')], max_length=20, verbose_name='نوع اتاق'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سرویس'),
        ),
    ]
