# Generated by Django 6.0.6 on 2026-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_invoice_deposit_paid_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.CharField(default='وای\u200cفای رایگان، سیستم سرمایش، تلویزیون ۴K، یخچال، مینی\u200cبار', max_length=250, verbose_name='امکانات اتاق (با کاما جدا شود)'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اتاق'),
        ),
    ]
