# Generated by Django 6.0.6 on 2026-06-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_amenities_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان عکس (مثلا: نمای لابی)')),
                ('image', models.ImageField(upload_to='hotel_gallery/', verbose_name='فایل عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='عکس اتاق')),
                ('is_main', models.BooleanField(default=False, verbose_name='عکس اصلی (کاور)؟')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room')),
            ],
        ),
    ]
