# Generated by Django 6.0.6 on 2026-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotelgallery_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آیتم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (ترکیبات)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('category', models.CharField(choices=[('restaurant', 'منوی رستوران'), ('bar', 'بار و نوشیدنی\u200cها')], max_length=20, verbose_name='دسته بندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود در منو')),
            ],
        ),
    ]
